// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/yangpei01/study/AwesomeProject/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/yangpei01/study/AwesomeProject/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/yangpei01/study/AwesomeProject/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('AwesomeProject', appParameters);
});